services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  employee-service:
    build: ./employee-service
    container_name: employee-service
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017
    ports:
      - "8001:8000"
    depends_on:
      - mongo

  project-allocation-service:
    build: ./project-allocation-service
    container_name: project-allocation-service
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017
    ports:
      - "8002:8001"
    depends_on:
      - mongo

volumes:
  data: